### Evocrash version 1.0.0-SNAPSHOT

### Results

The empty tests RemoteObjectSet_ESTest.java and RemoteObjectSet_ESTest_scaffolding.java were generated by Evocrash from the log.

### Tested log

```
org.objectweb.proactive.core.exceptions.IOException6: Failed to send PNP message to pnp://10.0.137.112:1025/PA-AGENT_NODE_1
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:106)
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObject.receiveMessage(PNPRemoteObject.java:71)	
        at org.objectweb.proactive.core.remoteobject.RemoteObjectSet.receiveMessage(RemoteObjectSet.java:194)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectAdapter.receiveMessage(RemoteObjectAdapter.java:140)
        at org.objectweb.proactive.core.remoteobject.SynchronousProxy.reify(SynchronousProxy.java:70)
        at pa.stub.org.objectweb.proactive.core.runtime._StubProActiveRuntime.getActiveObjects(_StubProActiveRuntime.java)
        at org.objectweb.proactive.core.runtime.ProActiveRuntimeRemoteObjectAdapter.getActiveObjects(ProActiveRuntimeRemoteObjectAdapter.java:109)
        at org.objectweb.proactive.core.node.NodeImpl.getNumberOfActiveObjects(NodeImpl.java:167)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource$1.run(NodeSource.java:746)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

### Exception

```
* EvoCrash: the generated test case:
ArrayList<URI> arrayList0 = new ArrayList<URI>();
ArrayList<URI> arrayList1 = new ArrayList<URI>();
ArrayList<URI> arrayList2 = new ArrayList<URI>();
ConcurrentHashMap<URI, Integer> concurrentHashMap0 = new ConcurrentHashMap<URI, Integer>();
ArrayList<URI> arrayList3 = new ArrayList<URI>();
EvoSuiteFile evoSuiteFile0 = null;
boolean boolean0 = false;
EvoSuiteFile evoSuiteFile1 = null;
EvoSuiteFile evoSuiteFile2 = null;
FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
String string0 = "The object isn't exposed on protocol ";
String string1 = "X@8XK\\";
RemoteRemoteObject remoteRemoteObject0 = null;
boolean boolean1 = true;
boolean boolean2 = false;
LinkedBlockingQueue<RemoteRemoteObject> linkedBlockingQueue0 = new LinkedBlockingQueue<RemoteRemoteObject>();
MinguoChronology minguoChronology0 = MinguoChronology.INSTANCE;
String string2 = " is not a directory";
long long0 = (-564L);
long long1 = 1785L;
long long2 = (-1L);
long long3 = (-454L);
minguoChronology0.dateEpochDay(long3);
String string3 = "";
FileSystemHandling.shouldAllThrowIOExceptions();
RemoteObjectSet remoteObjectSet0 = new RemoteObjectSet(remoteRemoteObject0, linkedBlockingQueue0);
Request request0 = null;
remoteObjectSet0.receiveMessage(request0);
String string4 = "ih:3Ei#O%_";
RemoteObjectSet remoteObjectSet1 = new RemoteObjectSet(remoteRemoteObject0, linkedBlockingQueue0);
RemoteObjectExposer<MinguoDate> remoteObjectExposer0 = new RemoteObjectExposer<MinguoDate>();
RemoteObjectSet remoteObjectSet2 = remoteObjectExposer0.getRemoteObjectSet(remoteRemoteObject0);
remoteObjectSet2.receiveMessage(request0);
String string5 = "";
URI uRI0 = new URI(string5);

>>>>>>>>>>>>>>>>>>>>>>>>>>>GGA was done in 601!<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

! Budget exceeded
! Unable to cover goal 0 org.crash.client.crashcoverage.CrashCoverageTestFitness@71326f58
* Search finished after 604s, 604 statements, best individual has fitness 0.0
* Covered 0/1 goals
* Target exception was set to: org.objectweb.proactive.core.exceptions.IOException6
* EvoCrash: The target call is either public or protected!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> The retrived call(s) to inject in the tests are:
>>>>>> receiveMessage
[MASTER] 17:46:21.925 [logback-1] WARN  TimeController - Phase INITIALIZATION lasted too long, 496 seconds more than allowed.
* Target exception was set to: org.objectweb.proactive.core.exceptions.IOException6
* EvoCrash: The target call is either public or protected!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> The retrived call(s) to inject in the tests are:
>>>>>> receiveMessage
* Minimizing test suite
* Going to analyze the coverage criteria
* Coverage analysis for criterion CRASH
* Target exception was set to: org.objectweb.proactive.core.exceptions.IOException6
* EvoCrash: The target call is either public or protected!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> The retrived call(s) to inject in the tests are:
>>>>>> receiveMessage
* Coverage of criterion CRASH: 0 %
* Total number of goals: 1
* Number of covered goals: 0
* Generated 0 tests with total length 0
* Resulting test suite's coverage: 0 %
* Generating assertions
* Resulting test suite's mutation score: 0 %
* Compiling and checking tests
* Permissions denied during test execution:
  - java.lang.RuntimePermission:
           loadLibrary.libsigar-amd64-linux.so: 1
	     - java.net.SocketPermission:
	              listen,resolve localhost:0: 180
		      * Writing JUnit test case 'RemoteObjectSet_ESTest' to src/GGA-tests/java
		      * Done!

* Computation finished
Exception in thread "main" java.lang.AssertionError: expected:<0.0> but was:<5.957142857142857>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:553)
    at org.junit.Assert.assertEquals(Assert.java:683)
    at eu.stamp_project.evocrash.demo.TestCreation.create(TestCreation.java:97)
    at eu.stamp_project.evocrash.demo.Application.main(Application.java:6)
```